import { TAX_RATE } from "@/constants/defaults";

// Fallback data for when Sanity is not available
export const fallbackData = {
  brands: [
    {
      _id: "brand-1",
      _type: "brand",
      name: "Havells",
      slug: { current: "havells" },
      description: "Leading electrical equipment manufacturer",
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "brand-2",
      _type: "brand",
      name: "Anchor",
      slug: { current: "anchor" },
      description: "Trusted electrical solutions",
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "brand-3",
      _type: "brand",
      name: "Legrand",
      slug: { current: "legrand" },
      description: "Premium electrical accessories",
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  categories: [
    {
      _id: "cat-1",
      _type: "category",
      name: "Switches & Sockets",
      slug: { current: "switches-sockets" },
      description: "Electrical switches and power sockets",
      icon: "power",
      isActive: true,
      sortOrder: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "cat-2",
      _type: "category",
      name: "Wires & Cables",
      slug: { current: "wires-cables" },
      description: "Electrical wiring and cables",
      icon: "cable",
      isActive: true,
      sortOrder: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "cat-3",
      _type: "category",
      name: "LED Lights",
      slug: { current: "led-lights" },
      description: "LED lighting solutions",
      icon: "lightbulb",
      isActive: true,
      sortOrder: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  products: [
    {
      _id: "prod-1",
      _type: "product",
      productId: "PROD-001",
      name: "6A Switch",
      slug: { current: "6a-switch" },
      description: "Standard 6 ampere electrical switch",
      brand: {
        _id: "brand-1",
        name: "Havells",
        slug: { current: "havells" },
        isActive: true,
      },
      category: {
        _id: "cat-1",
        name: "Switches & Sockets",
        slug: { current: "switches-sockets" },
        isActive: true,
      },
      specifications: {
        voltage: "220V",
        amperage: "6A",
        material: "Plastic",
        color: "White",
      },
      pricing: {
        purchasePrice: 45,
        sellingPrice: 65,
        mrp: 75,
        discount: 0,
        taxRate: TAX_RATE,
        unit: "piece",
      },
      inventory: {
        currentStock: 50,
        minimumStock: 10,
        maximumStock: 100,
        reorderLevel: 15,
        location: "Shelf A1",
      },
      images: [],
      isActive: true,
      isFeatured: true,
      tags: ["switch", "electrical", "6a"],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "prod-2",
      _type: "product",
      productId: "PROD-002",
      name: "2.5mm Wire",
      slug: { current: "2-5mm-wire" },
      description: "2.5mm electrical wire for home wiring",
      brand: {
        _id: "brand-2",
        name: "Anchor",
        slug: { current: "anchor" },
        isActive: true,
      },
      category: {
        _id: "cat-2",
        name: "Wires & Cables",
        slug: { current: "wires-cables" },
        isActive: true,
      },
      specifications: {
        wireGauge: "2.5mm",
        voltage: "220V",
        material: "Copper",
        color: "Red",
      },
      pricing: {
        purchasePrice: 120,
        sellingPrice: 150,
        mrp: 180,
        discount: 0,
        taxRate: TAX_RATE,
        unit: "meter",
      },
      inventory: {
        currentStock: 200,
        minimumStock: 50,
        maximumStock: 500,
        reorderLevel: 75,
        location: "Shelf B2",
      },
      images: [],
      isActive: true,
      isFeatured: false,
      tags: ["wire", "cable", "2.5mm"],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "prod-3",
      _type: "product",
      productId: "PROD-003",
      name: "9W LED Bulb",
      slug: { current: "9w-led-bulb" },
      description: "9 watt LED bulb with warm white light",
      brand: {
        _id: "brand-3",
        name: "Legrand",
        slug: { current: "legrand" },
        isActive: true,
      },
      category: {
        _id: "cat-3",
        name: "LED Lights",
        slug: { current: "led-lights" },
        isActive: true,
      },
      specifications: {
        watts: 9,
        voltage: "220V",
        lightType: "led",
        color: "warm-white",
        lumens: 900,
      },
      pricing: {
        purchasePrice: 85,
        sellingPrice: 120,
        mrp: 150,
        discount: 0,
        taxRate: TAX_RATE,
        unit: "piece",
      },
      inventory: {
        currentStock: 5, // Low stock for demo
        minimumStock: 20,
        maximumStock: 100,
        reorderLevel: 25,
        location: "Shelf C1",
      },
      images: [],
      isActive: true,
      isFeatured: true,
      tags: ["led", "bulb", "9w", "warm-white"],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  users: [
    {
      _id: "user-1",
      _type: "user",
      clerkId: "clerk-demo-1",
      customerId: "CUST-001",
      secretKey: "demo-key-1",
      name: "John Doe",
      email: "john@example.com",
      phone: "+91 7015493276",
      location: "Mumbai, Maharashtra",
      role: "customer" as const,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "user-2",
      _type: "user",
      clerkId: "clerk-demo-2",
      customerId: "CUST-002",
      secretKey: "demo-key-2",
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+91 9876543211",
      location: "Delhi, India",
      role: "customer" as const,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  bills: [
    {
      _id: "bill-1",
      _type: "bill",
      billId: "BILL-001",
      billNumber: "BILL-2024-0001",
      customer: {
        _id: "user-1",
        name: "John Doe",
        phone: "+91 7015493276",
        email: "john@example.com",
        location: "Mumbai, Maharashtra",
        role: "customer" as const,
      },
      items: [],
      serviceType: "sale" as const,
      locationType: "shop" as const,
      serviceDate: new Date().toISOString(),
      homeVisitFee: 0,
      transportationFee: 0,
      laborCharges: 0,
      subtotal: 185,
      taxAmount: 33.3,
      discountAmount: 0,
      totalAmount: 218.3,
      paymentStatus: "paid" as const,
      paymentMethod: "cash",
      paidAmount: 218.3,
      balanceAmount: 0,
      status: "completed" as const,
      priority: "medium" as const,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: "bill-2",
      _type: "bill",
      billId: "BILL-002",
      billNumber: "BILL-2024-0002",
      customer: {
        _id: "user-2",
        name: "Jane Smith",
        phone: "+91 9876543211",
        email: "jane@example.com",
        location: "Delhi, India",
        role: "customer" as const,
      },
      items: [],
      serviceType: "repair" as const,
      locationType: "home" as const,
      serviceDate: new Date().toISOString(),
      homeVisitFee: 200,
      transportationFee: 50,
      laborCharges: 300,
      subtotal: 550,
      taxAmount: 99,
      discountAmount: 0,
      totalAmount: 649,
      paymentStatus: "pending" as const,
      paymentMethod: undefined,
      paidAmount: 0,
      balanceAmount: 649,
      status: "in_progress" as const,
      priority: "high" as const,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
