export const locationOptions = [
  { value: "lilas", label: "Lilas" },
  { value: "sainiwas", label: "Sainiwas" },
  { value: "dhani-silawali", label: "Dhani Silawali" },
  { value: "siwani", label: "Siwani" },
  { value: "barwa", label: "Barwa" },
  { value: "talwandi ", label: "Talwandi " },
  { value: "gaindawas", label: "Gaindawas" },
  { value: "gurera", label: "Gurera" },
];

export const SECTION_SETS = {
  underground_before: [
    {
      title: "Fan Box & Conseild Box",
      items: ["Fan Box", "Conseild Box"],
    },
    {
      title: "Pype & Bends",
      items: ["Havey Pype", "Bends", "Hexa Blade/Aari Blade"],
    },
  ],
  underground_after: [
    {
      title: "Boards / Pypes",
      items: [
        `Normal Pype`,
        "Bends",
        "Junction Box",
        "Mcb Box 4way",
        "Mcb Box 6way",
        "Mcb Box 8way",
        "Mcb Box 10way",
        "Mcb Box 16way",
        "Mcb Box 24way",
        "Board 3x3",
        "Board 4x3",
        "Board 5x3",
        "Board 8x3",
        "Board 5x5",
        "Board 8x6",
        "Board 8x10",
        "Cutter Blade 6inch",
      ],
    },
  ],
  underground_wireing: [
    {
      title: "Switches & Sockets",
      items: [
        "6A Switch",
        "6A Socket",
        "16A Power Socket",
        "16A Power Switch",
        "Regulator",
        "Holder",
        "Indicator",
        "Dummey Plate",
        "TV Socket",
        "Round Seat",
        "Fan Seat",
        "MCB 10A",
        "MCB 16A",
        "MCB 32A",
        "Isolater 32A",
        "Isolater 40A",
        "Isolater 64A",
        "Changeovevr 16A",
        "Changeovevr 32A",
        "Changeovevr 40A",
        "Changeovevr 64A",
        "RCCB 32A",
        "RCCB 40A",
        "RCCB 64A",
      ],
    },
    {
      title: "Boards Seat / MCB",
      items: [
        "Board 3x3",
        "Board 4x3",
        "Board 5x3",
        "Board 8x3",
        "Board 5x5",
        "Board 8x6",
        "Board 8x10",
      ],
    },
    {
      title: "Wires",
      items: [
        "Wire 1.0 sqmm Copper",
        "Wire 1.5 sqmm Copper",
        "Wire 2.5 sqmm Copper",
        "Wire 4.0 sqmm Copper",
        "Wire 6.0 sqmm Copper",
        "Wire 4.0 sqmm Aluminuem",
        "Wire 6.0 sqmm Aluminuem",
        "Wire 10.0 sqmm Aluminuem",
        "Wire 16.0 sqmm Aluminuem",
      ],
    },
    {
      title: "Patches / Tape",
      items: [
        'Black Screws 1.5"',
        'Black Screws 2"',
        'Black Screws 2.5"',
        'Brass Screws 1.5"',
        'Brass Screws 2"',
        'Brass Screws 2.5"',
        "Tape Role 15mtr",
        "Jointer Normal",
        "Jointer 16~32amp",
        "Batten Gitti",
        "Pvc Gitti 40mm",
        "Wire Clip 4mm",
        "Wire Clip 6mm",
        "Wire Clip 10mm",
        "Wire Clip 16mm",
        "Wire Clip 25mm",
      ],
    },
  ],
  open_pvc: [
    {
      title: "Switches & Sockets",
      items: [
        "6A Switch",
        "6A Socket",
        "16A Power Socket",
        "16A Power Switch",
        "Regulator",
        "Holder",
        "Ceiling Rose",
        "Round Block",
        "Indicator",
        "Dummey Plate",
        "MCB 10A",
        "MCB 16A",
        "MCB 32A",
        "Isolater 32A",
        "Isolater 40A",
        "Isolater 64A",
        "Changeovevr 16A",
        "Changeovevr 32A",
        "Changeovevr 40A",
        "Changeovevr 64A",
        "RCCB 32A",
        "RCCB 40A",
        "RCCB 64A",
      ],
    },
    {
      title: "Boards / PVC Casing",
      items: [
        `Fatti 0.5"`,
        `Fatti 1"`,
        "Board 3x3",
        "Board 4x3",
        "Board 5x3",
        "Board 8x3",
        "Board 5x5",
        "Board 8x6",
        "Board 8x10",
        "Mcb Box 4way",
        "Mcb Box 6way",
        "Mcb Box 8way",
      ],
    },
    {
      title: "Wires",
      items: [
        "Wire 1.0 sqmm Copper",
        "Wire 1.5 sqmm Copper",
        "Wire 2.5 sqmm Copper",
        "Wire 4.0 sqmm Copper",
        "Wire 6.0 sqmm Copper",
        "Wire 4.0 sqmm Aluminuem",
        "Wire 6.0 sqmm Aluminuem",
        "Wire 10.0 sqmm Aluminuem",
        "Wire 16.0 sqmm Aluminuem",
      ],
    },
    {
      title: "Patches / Tape",
      items: [
        ' Black Screws 0.5"',
        ' Black Screws 1"',
        ' Black Screws 1.5"',
        ' Black Screws 2"',
        ' Black Screws 2.5"',
        "Tape Role 15mtr",
        "Batten Keel",
        "Pvc Gitti 40mm",
        "Wire Clip 4mm",
        "Wire Clip 6mm",
        "Wire Clip 10mm",
        "Wire Clip 16mm",
        "Wire Clip 25mm",
        "Gatter Patti",
        "Jointer Normal",
        "Jointer 16~32amp",
      ],
    },
  ],
};
